#include <windows.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>

// Forward declarations for MinHook
#include "MinHook.h"
#pragma comment(lib, "libMinHook.x64.lib")

// The signature of the decryption function we found in IDA
// __int64 __fastcall sub_1412AEBC0(__int64 a1, void *a2, size_t a3, __int64 a4, __int64 a5)
typedef __int64(__fastcall* DecryptBlockFn)(__int64 ctx, void* buffer, size_t size, __int64 a4, __int64 a5);
DecryptBlockFn OriginalDecryptBlock = nullptr;

// We will load our replacement targets from a config file
std::string targetItemStr = "";
std::string replacementItemStr = "";

// The Hook Function
__int64 __fastcall HookedDecryptBlock(__int64 ctx, void* buffer, size_t size, __int64 a4, __int64 a5) {
    // 1. Call the original function so the AES-CTR engine does the heavy lifting
    __int64 result = OriginalDecryptBlock(ctx, buffer, size, a4, a5);

    // 2. We now have decrypted data in `buffer` with length `size`.
    // We can scan it for our target FName/Asset paths.
    if (size > 0 && targetItemStr.length() > 0 && replacementItemStr.length() > 0) {
        char* charBuffer = static_cast<char*>(buffer);
        size_t targetLen = targetItemStr.length();
        
        // Simple linear search for the target string
        for (size_t i = 0; i <= size - targetLen; ++i) {
            bool match = true;
            for (size_t j = 0; j < targetLen; ++j) {
                if (charBuffer[i + j] != targetItemStr[j]) {
                    match = false;
                    break;
                }
            }
            
            // If we found the target string, replace it!
            if (match) {
                // WARNING: We must not change the length of the string, or we break the UPK structure!
                // For a robust implementation, the user needs to pad the replacement string to match the target string length,
                // or we need to intercept the FName table length prefix as well (which is 4 bytes before the string).
                
                size_t replaceLen = replacementItemStr.length();
                size_t copyLen = (replaceLen < targetLen) ? replaceLen : targetLen;
                
                for(size_t k = 0; k < copyLen; k++) {
                    charBuffer[i + k] = replacementItemStr[k];
                }
                
                // Pad with null bytes if the replacement is shorter
                for(size_t k = copyLen; k < targetLen; k++) {
                     charBuffer[i + k] = '\0';
                }
                
                // Skip ahead to avoid overlapping replaces
                i += targetLen - 1; 
            }
        }
    }

    return result;
}

void LoadConfig() {
    // Read the payload config generated by the Python script
    std::ifstream configFile("C:\\Users\\musta\\Downloads\\RLTM\\RLItemMod\\payload_config.txt");
    if (configFile.is_open()) {
        std::getline(configFile, targetItemStr);
        std::getline(configFile, replacementItemStr);
        configFile.close();
    }
}

DWORD WINAPI MainThread(LPVOID lpParam) {
    LoadConfig();

    // Initialize MinHook
    if (MH_Initialize() != MH_OK) {
        return 1;
    }

    // Get the base address of RocketLeague.exe
    uintptr_t baseAddress = (uintptr_t)GetModuleHandle(NULL);
    
    // The target function offset (0x1412AEBC0 - 0x140000000 = 0x12AEBC0)
    // Adjust this if Rocket League is updated!
    uintptr_t targetAddress = baseAddress + 0x12AEBC0;

    // Create the hook
    if (MH_CreateHook((LPVOID)targetAddress, &HookedDecryptBlock, reinterpret_cast<LPVOID*>(&OriginalDecryptBlock)) != MH_OK) {
        return 1;
    }

    // Enable the hook
    if (MH_EnableHook((LPVOID)targetAddress) != MH_OK) {
        return 1;
    }

    return 0;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved) {
    switch (ul_reason_for_call) {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(hModule);
        CreateThread(nullptr, 0, MainThread, hModule, 0, nullptr);
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
